// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/google/uuid"
)

type InviteCode struct {
	CodeID uuid.UUID `json:"code_id"`
	Code   string    `json:"code"`
	Active bool      `json:"active"`
}

type User struct {
	UserID       uuid.UUID `json:"user_id"`
	TelegramID   string    `json:"telegram_id"`
	InviteCodeID uuid.UUID `json:"invite_code_id"`
}
